"""Probabilistic tractography -> ROI structural connectivity.

Two back-ends:

* **MRtrix3** (preferred, state of the art): a per-subject bash script is generated (denoise,
  Gibbs unringing, [FSL eddy], bias correction, dhollander response, (MSMT-)CSD, iFOD2 with
  anatomically constrained tractography when a T1w is available, SIFT2, tck2connectome).
  Run it with ``execute=True`` or submit it to your scheduler.
* **DIPY** (pure Python fallback): CSD + probabilistic direction getter + FA-thresholded local
  tracking, atlas registered with DIPY's affine/SyN registration, connectivity via the same
  accumulation code as the normative connectome.
"""
from __future__ import annotations

import os
import shlex
import stat
import subprocess
from pathlib import Path

import nibabel as nib
import numpy as np

from ..atlases import Atlas
from ..utils import LOG, ensure_dir, save_json, which
from .common import accumulate_pairs, endpoint_pairs, normalise_matrices, sc_summary


def detect_backend(preferred: str = "auto") -> str:
    if preferred != "auto":
        return preferred
    if which("tckgen") and which("dwi2fod"):
        return "mrtrix"
    try:
        import dipy  # noqa: F401

        return "dipy"
    except Exception:  # noqa: BLE001
        raise RuntimeError("neither MRtrix3 (tckgen) nor DIPY is available for tractography")


# ------------------------------------------------------------------ MRtrix3 script
def mrtrix_script(dwi: Path, bval: Path | None, bvec: Path | None, out_dir: Path, atlas_dwi: Path | None, cfg: dict,
                  mask: Path | None = None, t1w: Path | None = None, preprocessed: bool = True, pe_dir: str | None = None,
                  grad_mrtrix: Path | None = None, nthreads: int = 4) -> str:
    """Return the text of a bash script running the MRtrix3 pipeline for one subject."""
    n = int(cfg.get("n_streamlines", 10_000_000))
    cutoff = float(cfg.get("fod_cutoff", 0.06))
    maxlen = float(cfg.get("max_length", 250.0))
    minlen = float(cfg.get("min_length", 10.0))
    angle = float(cfg.get("max_angle", 45.0))
    step = cfg.get("step_size")
    sift2 = bool(cfg.get("sift2", True))
    act = cfg.get("act", "auto")
    use_act = (act is True or act == "auto") and t1w is not None
    grad = f"-grad {shlex.quote(str(grad_mrtrix))}" if grad_mrtrix else f"-fslgrad {shlex.quote(str(bvec))} {shlex.quote(str(bval))}"
    L = ["#!/usr/bin/env bash", "# MRtrix3 tractography pipeline generated by hopfec (review before running)", "set -euo pipefail",
         f"export MRTRIX_NTHREADS={nthreads}", f"OUT={shlex.quote(str(out_dir))}", "mkdir -p \"$OUT\"", "cd \"$OUT\"", "",
         f"mrconvert {shlex.quote(str(dwi))} dwi.mif {grad} -force"]
    if not preprocessed:
        L += ["dwidenoise dwi.mif dwi_den.mif -force", "mrdegibbs dwi_den.mif dwi_den_unr.mif -force"]
        if which("eddy") or which("eddy_openmp") or which("eddy_cpu"):
            pe = pe_dir or "AP"
            L += [f"dwifslpreproc dwi_den_unr.mif dwi_preproc.mif -rpe_none -pe_dir {pe} -eddy_options \" --slm=linear\" -force"]
        else:
            L += ["echo 'WARNING: FSL eddy not found - skipping motion/eddy correction'", "cp dwi_den_unr.mif dwi_preproc.mif"]
        L += ["dwibiascorrect ants dwi_preproc.mif dwi_unbiased.mif -force || cp dwi_preproc.mif dwi_unbiased.mif"]
    else:
        L += ["cp dwi.mif dwi_unbiased.mif"]
    if mask:
        L += [f"mrconvert {shlex.quote(str(mask))} mask.mif -force"]
    else:
        L += ["dwi2mask dwi_unbiased.mif mask.mif -force"]
    L += ["dwiextract dwi_unbiased.mif -bzero - | mrmath - mean b0.mif -axis 3 -force",
          "mrconvert b0.mif b0.nii.gz -force",
          "# response functions and FODs (multi-shell multi-tissue when possible)",
          "dwi2response dhollander dwi_unbiased.mif wm.txt gm.txt csf.txt -mask mask.mif -force",
          "NSHELL=$(mrinfo dwi_unbiased.mif -shell_bvalues | wc -w)",
          "if [ \"$NSHELL\" -ge 3 ]; then",
          "  dwi2fod msmt_csd dwi_unbiased.mif wm.txt wmfod.mif gm.txt gm.mif csf.txt csf.mif -mask mask.mif -force",
          "  mtnormalise wmfod.mif wmfod_norm.mif gm.mif gm_norm.mif csf.mif csf_norm.mif -mask mask.mif -force",
          "else",
          "  dwi2fod msmt_csd dwi_unbiased.mif wm.txt wmfod.mif csf.txt csf.mif -mask mask.mif -force",
          "  mtnormalise wmfod.mif wmfod_norm.mif csf.mif csf_norm.mif -mask mask.mif -force",
          "fi"]
    seed = "-seed_dynamic wmfod_norm.mif"
    act_opt = ""
    if use_act:
        L += [f"# anatomically constrained tractography from the T1w (assumed aligned with the DWI)",
              f"5ttgen fsl {shlex.quote(str(t1w))} 5tt.mif -force || 5ttgen freesurfer {shlex.quote(str(t1w))} 5tt.mif -force",
              "5tt2gmwmi 5tt.mif gmwmi.mif -force"]
        act_opt = "-act 5tt.mif -backtrack -crop_at_gmwmi"
        seed = "-seed_gmwmi gmwmi.mif"
    stepopt = f"-step {step}" if step else ""
    L += [f"tckgen wmfod_norm.mif tracks.tck -algorithm iFOD2 -select {n} -cutoff {cutoff} -minlength {minlen} -maxlength {maxlen} -angle {angle} {stepopt} {seed} {act_opt} -force"]
    w = ""
    if sift2:
        L += [f"tcksift2 tracks.tck wmfod_norm.mif sift2_weights.txt {('-act 5tt.mif' if use_act else '')} -force"]
        w = "-tck_weights_in sift2_weights.txt"
    if atlas_dwi is not None:
        assign = "-assignment_radial_search 2" if cfg.get("endpoints_only", True) else "-assignment_all_voxels"
        L += ["# connectomes: SIFT2-weighted count, mean length, inverse-node-volume scaled",
              f"tck2connectome tracks.tck {shlex.quote(str(atlas_dwi))} sc_count.csv {w} {assign} -symmetric -zero_diagonal -out_assignments assignments.txt -force",
              f"tck2connectome tracks.tck {shlex.quote(str(atlas_dwi))} sc_meanlength.csv {w} {assign} -symmetric -zero_diagonal -scale_length -stat_edge mean -force",
              f"tck2connectome tracks.tck {shlex.quote(str(atlas_dwi))} sc_invnodevol.csv {w} {assign} -symmetric -zero_diagonal -scale_invnodevol -force",
              f"tck2connectome tracks.tck {shlex.quote(str(atlas_dwi))} sc_invlength.csv {w} {assign} -symmetric -zero_diagonal -scale_invlength -force"]
    else:
        L += ["echo 'No atlas in DWI space given: run hopfec sc tractography with an atlas to build the connectome'"]
    L += ["echo DONE"]
    return "\n".join(L) + "\n"


def ants_warp_atlas_script(atlas_mni: Path, template_t1: Path, subject_t1: Path, out_dir: Path, ref_image: Path | None = None,
                           existing_xfm: Path | None = None) -> str:
    """Bash snippet registering MNI -> subject T1w with ANTs (or using an existing h5 transform) and warping the atlas."""
    L = ["# --- atlas (MNI) -> subject space with ANTs", f"cd {shlex.quote(str(out_dir))}"]
    ref = ref_image or subject_t1
    if existing_xfm:
        L += [f"antsApplyTransforms -d 3 -i {shlex.quote(str(atlas_mni))} -r {shlex.quote(str(ref))} -o atlas_in_dwi.nii.gz -n GenericLabel -t {shlex.quote(str(existing_xfm))}"]
    else:
        L += [f"antsRegistrationSyNQuick.sh -d 3 -f {shlex.quote(str(subject_t1))} -m {shlex.quote(str(template_t1))} -o mni2sub_ -n 4",
              f"antsApplyTransforms -d 3 -i {shlex.quote(str(atlas_mni))} -r {shlex.quote(str(ref))} -o atlas_in_dwi.nii.gz -n GenericLabel -t mni2sub_1Warp.nii.gz -t mni2sub_0GenericAffine.mat"]
    return "\n".join(L) + "\n"


def write_script(text: str, path: Path) -> Path:
    ensure_dir(path.parent)
    path.write_text(text)
    path.chmod(path.stat().st_mode | stat.S_IXUSR)
    return path


def run_script(path: Path, log: Path | None = None) -> int:
    LOG.info("running %s", path)
    with open(log or path.with_suffix(".log"), "w") as f:
        return subprocess.call(["bash", str(path)], stdout=f, stderr=subprocess.STDOUT)


def read_mrtrix_connectome(csv: Path) -> np.ndarray:
    return np.loadtxt(csv, delimiter=",")


# ------------------------------------------------------------------ DIPY pipeline
def register_atlas_to_dwi_dipy(atlas: Atlas, template_t1: Path, b0: nib.Nifti1Image, t1w: nib.Nifti1Image | None = None,
                               syn: bool = True) -> nib.Nifti1Image:
    """Bring the atlas labels into the subject DWI grid with DIPY (affine MI [+ SyN when a T1w is given])."""
    from dipy.align import affine_registration, syn_registration
    from dipy.align.imaffine import AffineMap

    tpl_img = nib.load(str(template_t1))
    tpl = np.asarray(tpl_img.dataobj, float)
    lab_img = atlas.load_img()
    lab = np.rint(np.asarray(lab_img.dataobj)).astype(np.int32)
    static_img = t1w if t1w is not None else b0
    static = np.asarray(static_img.dataobj, float)
    if static.ndim == 4:
        static = static[..., 0]
    pipeline = ["center_of_mass", "translation", "rigid", "affine"]
    _, aff = affine_registration(tpl, static, moving_affine=tpl_img.affine, static_affine=static_img.affine, pipeline=pipeline,
                                 level_iters=[10000, 1000, 100], sigmas=[3.0, 1.0, 0.0], factors=[4, 2, 1])
    amap = AffineMap(aff, static.shape, static_img.affine, lab.shape, lab_img.affine)
    if syn and t1w is not None:
        warped_tpl, mapping = syn_registration(tpl, static, moving_affine=tpl_img.affine, static_affine=static_img.affine,
                                               prealign=aff, level_iters=[10, 10, 5], metric="CC")
        lab_sub = mapping.transform(lab, interpolation="nearest")
    else:
        lab_sub = amap.transform(lab, interpolation="nearest")
    lab_sub = np.rint(lab_sub).astype(np.int32)
    if t1w is not None and (t1w.shape[:3] != b0.shape[:3] or not np.allclose(t1w.affine, b0.affine, atol=1e-3)):
        # T1w -> b0 rigid (cross-modal MI), then resample labels onto the DWI grid
        b0d = np.asarray(b0.dataobj, float)
        if b0d.ndim == 4:
            b0d = b0d[..., 0]
        _, aff2 = affine_registration(static, b0d, moving_affine=t1w.affine, static_affine=b0.affine,
                                      pipeline=["center_of_mass", "translation", "rigid"], level_iters=[1000, 100], sigmas=[2.0, 0.0], factors=[2, 1])
        amap2 = AffineMap(aff2, b0d.shape, b0.affine, lab_sub.shape, t1w.affine)
        lab_sub = np.rint(amap2.transform(lab_sub, interpolation="nearest")).astype(np.int32)
        return nib.Nifti1Image(lab_sub, b0.affine)
    return nib.Nifti1Image(lab_sub, static_img.affine)


def streamlines_to_connectivity(streamlines, labels_img: nib.Nifti1Image, atlas_ids: np.ndarray, endpoints_only: bool = True,
                                length_weighting: bool = True) -> dict:
    """ROI x ROI matrices from streamlines (world mm coordinates) and a label image."""
    lab = np.rint(np.asarray(labels_img.dataobj)).astype(np.int64)
    lab[lab < 0] = 0
    inv = np.linalg.inv(labels_img.affine)
    pos = np.full(int(lab.max()) + 1, -1, np.int64)
    for k, l in enumerate(atlas_ids):
        if int(l) < len(pos):
            pos[int(l)] = k
    n_roi = len(atlas_ids)
    lengths = []
    firsts, lasts, sids, labidx = [], [], [], []
    for s_id, sl in enumerate(streamlines):
        pts = np.asarray(sl, float)
        if len(pts) < 2:
            continue
        L = float(np.sum(np.linalg.norm(np.diff(pts, axis=0), axis=1)))
        lengths.append(L)
        vox = np.rint((inv[:3, :3] @ pts.T + inv[:3, 3:4]).T).astype(np.int64)
        inside = np.all(vox >= 0, axis=1) & np.all(vox < np.array(lab.shape), axis=1)
        li = np.full(len(pts), 0, np.int64)
        li[inside] = lab[vox[inside, 0], vox[inside, 1], vox[inside, 2]]
        idx = np.where(li > 0, pos[np.minimum(li, len(pos) - 1)], -1)
        if endpoints_only:
            firsts.append(idx[0])
            lasts.append(idx[-1])
        else:
            keep = idx >= 0
            sids.append(np.full(keep.sum(), len(lengths) - 1))
            labidx.append(idx[keep])
    lengths = np.asarray(lengths)
    w = 1.0 / np.maximum(lengths, 1e-6) if length_weighting else None
    if endpoints_only:
        count, lenw, n_conn = endpoint_pairs(np.asarray(firsts), np.asarray(lasts), n_roi, w)
    else:
        count, lenw, n_conn = accumulate_pairs(np.concatenate(sids) if sids else np.zeros(0, int), np.concatenate(labidx) if labidx else np.zeros(0, int), len(lengths), n_roi, w)
    vols = np.array([np.sum(lab == int(l)) for l in atlas_ids], float)
    out = normalise_matrices(count, lenw, vols)
    out["roi_vol"] = vols
    out["n_streamlines"] = int(len(lengths))
    out["n_connecting_streamlines"] = int(n_conn)
    out["mean_length_mm"] = float(lengths.mean()) if len(lengths) else float("nan")
    return out


def run_dipy_tractography(dwi: Path, bval: Path, bvec: Path, out_dir: Path, atlas: Atlas, cfg: dict, mask: Path | None = None,
                          t1w: Path | None = None, template_t1: Path | None = None, atlas_in_dwi: Path | None = None,
                          seed: int = 0, save_trk: bool = False) -> dict:
    """CSD-based probabilistic tractography with DIPY and connectivity with the atlas."""
    from dipy.core.gradients import gradient_table
    from dipy.data import default_sphere
    from dipy.direction import ProbabilisticDirectionGetter
    from dipy.io.gradients import read_bvals_bvecs
    from dipy.reconst.csdeconv import ConstrainedSphericalDeconvModel, auto_response_ssst
    from dipy.reconst.dti import TensorModel
    from dipy.segment.mask import median_otsu
    from dipy.tracking import utils as tutils
    from dipy.tracking.local_tracking import LocalTracking
    from dipy.tracking.stopping_criterion import ThresholdStoppingCriterion
    from dipy.tracking.streamline import Streamlines

    out_dir = ensure_dir(out_dir)
    img = nib.load(str(dwi))
    data = np.asarray(img.dataobj, np.float32)
    bvals, bvecs = read_bvals_bvecs(str(bval), str(bvec))
    gtab = gradient_table(bvals, bvecs=bvecs)
    if mask is not None:
        m = np.asarray(nib.load(str(mask)).dataobj) > 0
    else:
        _, m = median_otsu(data, vol_idx=np.where(gtab.b0s_mask)[0], median_radius=3, numpass=1)
    b0 = nib.Nifti1Image(data[..., gtab.b0s_mask].mean(axis=3), img.affine)
    # atlas in DWI space
    if atlas_in_dwi is not None:
        lab_img = nib.load(str(atlas_in_dwi))
    else:
        if template_t1 is None:
            raise ValueError("template_t1 (MNI T1w matching the atlas space) is required to register the atlas")
        t1 = nib.load(str(t1w)) if t1w else None
        lab_img = register_atlas_to_dwi_dipy(atlas, Path(template_t1), b0, t1, syn=bool(cfg.get("syn", True)))
        nib.save(lab_img, out_dir / "atlas_in_dwi.nii.gz")
    # tensor for FA (seeding / stopping)
    ten = TensorModel(gtab).fit(data, mask=m)
    fa = np.nan_to_num(ten.fa)
    nib.save(nib.Nifti1Image(fa.astype(np.float32), img.affine), out_dir / "fa.nii.gz")
    fa_thr = float(cfg.get("fa_threshold", 0.15))
    # CSD
    response, _ = auto_response_ssst(gtab, data, roi_radii=10, fa_thr=0.7)
    n_dirs = int(np.sum(~gtab.b0s_mask))
    sh_order = 8 if n_dirs >= 45 else 6 if n_dirs >= 28 else 4
    csd = ConstrainedSphericalDeconvModel(gtab, response, sh_order_max=sh_order)
    csd_fit = csd.fit(data, mask=m)
    dg = ProbabilisticDirectionGetter.from_shcoeff(csd_fit.shm_coeff, max_angle=float(cfg.get("max_angle", 30.0)),
                                                  sphere=default_sphere, sh_to_pmf=True)
    stop = ThresholdStoppingCriterion(fa, 0.1)
    seed_mask = (fa > fa_thr) & m
    seeds = tutils.random_seeds_from_mask(seed_mask, img.affine, seeds_count=int(cfg.get("seeds_per_voxel", 2)),
                                          seed_count_per_voxel=True, random_seed=seed)
    step = float(cfg.get("step_size", 0.5))
    sl_gen = LocalTracking(dg, stop, seeds, img.affine, step_size=step, max_cross=1, return_all=False)
    streamlines = Streamlines(sl_gen)
    lengths = np.array([len(s) for s in streamlines]) * step
    keep = (lengths >= float(cfg.get("min_length", 10.0))) & (lengths <= float(cfg.get("max_length", 250.0)))
    streamlines = Streamlines([s for s, k in zip(streamlines, keep) if k])
    LOG.info("DIPY tracking: %d streamlines kept", len(streamlines))
    if save_trk:
        from dipy.io.stateful_tractogram import Space, StatefulTractogram
        from dipy.io.streamline import save_tractogram

        save_tractogram(StatefulTractogram(streamlines, img, Space.RASMM), str(out_dir / "tracks.trk"))
    res = streamlines_to_connectivity(streamlines, lab_img, atlas.label_ids, endpoints_only=bool(cfg.get("endpoints_only", True)))
    res["summary"] = sc_summary(res["count"], atlas.hemispheres)
    return res
